from dockerhub.private.wso2.com/jasintha-wso2is-bt:5.1.0

COPY is-server/carbon/ /mnt/wso2/carbon-home/

COPY artifacts/mysql-connector-java-5.1.34-bin.jar /mnt/wso2/carbon-home/repository/components/lib/
