from  dockerhub.private.wso2.com/jasintha-bt-wso2am-1.10.0-mysql:latest

COPY am-server/carbon/ /mnt/wso2/carbon-home/

COPY artifacts/mysql-connector-java-5.1.34-bin.jar /mnt/wso2/carbon-home/repository/components/lib/
